language: node_js
node_js:
  - '16'
addons:
  chrome: stable
env:
  global: CODECOV_TOKEN=$CODECOV_TOKEN
before_script:
  - npm install
jobs:
  include:
    - stage: Test coverage
      script:
        - ng test --browsers=ChromeHeadlessNoSandbox --code-coverage=true --watch=false
      after_script:
        - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${CODECOV_TOKEN}; fi
